### PR TITLE
Added MiP::stop and MiP::turnAngle

### PR DESCRIPTION
**Pull request by 2stacks**
I'm very new to git so excuse all of the unnecessary changes.  I'm very interested in helping with this project.  I started with a couple of the simpler functions just to make sure I understood how your library implements the WowWeeLabs MiP commands.

### CODE REVIEW

**Comment by Tiogaplanet** [comment]
2stacks, lmk if you want to keep working on this.  I'll contribute where ever I can.

**Comment by 2stacks** [comment]
Great, I'd be glad to work on this with you.  My C++ skills are limited but
I'm a quick study.  At the moment I'm trying to figure out how to read
serial data returned from the MiP.  The current library doesn't seem to
have anything to support this so I'm starting from scratch.

**Comment by Tiogaplanet** [comment]
I'm trying to figure the same thing out right now.  I can't seem to find the smallest snippet of code to hint on how to read data from the MiP.   I've been trying variations on generic Arduino serial reads but nothing seems to stick.  I'm new to Arduino and my C++ is rusty as hell.

There's this but I am having trouble making the jump from pure C to the Arduino library:

https://github.com/adamgreen/MiP

```
  From: 2stacks <notifications@github.com>
```

 To: sparkfun/SparkFun_MiP_Arduino_Library SparkFun_MiP_Arduino_Library@noreply.github.com 
Cc: Tiogaplanet samuel_trassare@yahoo.com
 Sent: Friday, January 22, 2016 10:53 AM
 Subject: Re: [SparkFun_MiP_Arduino_Library] Added MiP::stop and MiP::turnAngle (#1)

Great, I'd be glad to work on this with you. My C++ skills are limited but
I'm a quick study. At the moment I'm trying to figure out how to read
serial data returned from the MiP. The current library doesn't seem to
have anything to support this so I'm starting from scratch.

**Comment by Tiogaplanet** [comment]
I have a small script that can write the volume to the MiP and then read it back.  It's just a little something to help me understand how to read serial data back from the MiP.  The problem is, it frequently reads back incorrect results.  The following code:

`const int8_t _UART_Select_S = 2;
const int8_t _UART_Select_R = 3;

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  pinMode(_UART_Select_S, OUTPUT);
  pinMode(_UART_Select_R, INPUT);
  uint8_t array_length = 9;
  uint8_t data_array[] = "TTM:OK\r\n";
  sendMessage(data_array, array_length);
  uint8_t set_volume[2];
  set_volume[0] = 0x15;
  set_volume[1] = 0x03;
  sendMessage(set_volume, 2);
  Serial.println("SETUP");
}

void loop() {
  delay(1000);
  uint8_t question[1];
  question[0] = 0x16;
  sendMessage(question, 1);
  delay(3000);
  // put your main code here, to run repeatedly:
  if (Serial.available() > 0) {
    Serial.println(Serial.readString());
  }
  else {
    Serial.println("HELLO");
  }
}

void sendMessage(unsigned char *message, uint8_t array_length) {
  digitalWrite(_UART_Select_S, HIGH);
  //delay(5);
  uint8_t i = 0;
  for (i; i < array_length; i++) {
    Serial.write(message[i]);
  }
  Serial.write(0x00);
  delay(5);
  digitalWrite(_UART_Select_S, LOW);
}
`

produces these results with the COM monitor:

`SETUP
16šþ
16šþ
1šþ
16šþ
16šþ
16šþ
1š
1603
1š
1603
1603
1š
`

So I'm close (1603 is the expected result).  But unless I figure out how to overcome the bad data I won't be able to do much from here.  Any ideas?

**Comment by 2stacks** [comment]
I honestly have no idea. The only thing I can think of to try different is
to change;

if (Serial.available() > 0) {

to

while (Serial.available() > 0) {

You might be looping through and asking the question over again before the
MiP has fully answered the question each time.

I haven't spent much time on this lately but glad to see you have.  I can
borrow this and do some testing myself

I was going to write a function much like 'sendMessage' that selectively
reads data waiting in the serial buffer and places it in a string variable
or struct that can be parsed.  That was what I was going to attempt anyway.

Thanks!

**Comment by ToniCorinne** [comment]
Thanks for the additional example! I had to move both the example sketches into directories so they would show up properly in the Arduino IDE once the library is installed. 

Thanks again!

**Comment by 2stacks** [comment]
Thanks, I've merged the addition of the directories.  Looking forward
to pulling down Tiogaplanet's readMessage function.

**Comment by Tiogaplanet** [comment]
It goes without saying that `readMessage` still needs some (a lot of) polish.  I noticed after making the pull request that I should have combined the bytes from `Serial.read` into the actual MiP commands rather than storing each read byte into the `answer` buffer.  So that's what I'm working on next.  The change will affect how getter functions call `readMessage`.

**Pull request merged**
