### PR TITLE
Added error checking to getMessage

### PR DESCRIPTION
**Pull request by Tiogaplanet**
No error checking done in getMessage meant that occasional bad values
were slipping past getMessage and passed to getVolume.  Added a check to
make sure that what MiP was sending to getMessage was a valid ASCII
char.

Also, combined pairs of bytes to form the actual commands and responses
MiP intends.

Lastly, bumping up the retry value seemed to help a little.

### CODE REVIEW

**Comment by Tiogaplanet** [comment]
@ToniCorinne With what frequency do you want pull requests?  My ability to contribute will come in fits and starts but I don't want to inundate you with pull reqs.

I figure until the library reaches the point where it provides everything it's supposed to provide we could do pulls frequently.  But once it reaches the point where it provides all the getters and setters it's supposed to, we could switch to a kind of maintenance mode and only do pulls for bug fixes or incremental improvements.

What do you think?

**Comment by ToniCorinne** [comment]
Hey @Tiogaplanet - thanks again for all the hard work on this! We also have to balance working on many projects, so it may take us a bit of time to get to reviewing them, but please do keep contributing!

Regarding this particular pull request, do you mind updating the example sketches as you update the library? There's a few errors that are popping up with this current configuration, and I'd like to be able to verify these the way you are testing it.

**Comment by Tiogaplanet** [comment]
I think I'm starting to understand pull requests a little better.  At first I was under the impression that only the commits prior to my pull request would be sent upstream.  Now that I've submitted my second pull request I see that every commit I've done since the pull request also gets sent upstream.  That was not my intent.

I'm making major changes compared to what's in the upstream repo.  I intend to implement everything in the library in my own repo and include an example sketch that contains a full test suite.  Bottom line, I'll throttle back on pull requests to you for now.

What things are popping up right now?  That kind of feedback will give me a bit of direction.  Ever since implementing getMessage I haven't been to sure of what to work on next.

I appreciate your time.  I know you are busy with your day job. :)

**Comment by Tiogaplanet** [comment]
@ToniCorinne I added a test suite that is still being developed.  Not sure if you get notifications on commits to my branch.  Do you?

Anyway, I'm having trouble reading from the MiP any message beyond 4 bytes (4 characters sent from MiP UART).  After that four-character mark I start getting garbage.  I'm not sure where the problem lies.  My code?  Noise?  Arduino Serial library?  The MiP ProMini?

Lotsa questions from me.  Any ideas from y'all?

**Comment by ToniCorinne** [comment]
We don't get notifications of changes to the pull request after it has been submitted unless it is specifically being watched. However, you are correct that any changes you make to the same branch as your pull request will be sent upstream to us. If you'd rather only submit particular changes, you can close this pull request and open one that is off of a branch on your copy of the repository, and you can keep developing on master branch. 

Regarding the errors I was seeing - the example sketches will not compile due to the changes in the functions you've made. For example, in MiP Test, the line `MyMiP.playSingleSound(BURP);` is not recognized as an included function in the library since you've changed the structure of the Sound function. Those are types of things to check out and verify before submitting the pull request. 

Regarding the garbage characters you're getting back, I'd verify your array length for the command you are sending. You may just not be setting up the array properly to get the full message back.

**Comment by Tiogaplanet** [comment]
Just an update.  Did some debugging on `getMessage()`.  Still need to do some more testing and fix the examples per @ToniCorinne's message above.  If all goes well this push request can complete in the near future.

**Comment by Tiogaplanet** [comment]
@ToniCorinne After changing the interface for the class and doing a lot of debugging, I finally got the original test file and @2stacks' turn angle test example working again! :)  It's all in my head!  If you want to check it out I think you'll find that it gets us back to our original working position (meaning the robot can do all the things it was doing before) plus the library has a bunch of added capability that I now need to implement tests for.  That will be next.

If you find my latest work to be all in order please complete this pull request.

Thank you!

**Comment by Tiogaplanet** [comment]
@ToniCorinne It's been a couple weeks so I thought I'd follow up.  Is my work OK to complete this pull request?

**Pull request closed without merging**
